# platform :ios, '10.0'
workspace 'srpSDK'

def shared_pods
    pod 'SwiftyJSON', '~> 4.1.0'
    pod 'Alamofire', '~> 4.7.2'
    pod 'BigInt', '~> 3.1'
    pod 'BlueCryptor'
end

target 'srpSDKTestDemo' do
    project 'srpSDKTestDemo'
    shared_pods
end
target 'srpSDKFramework' do
    project '../srpSDKFramework/srpSDKFramework'
    shared_pods
end
